###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.7"
services:

    redis:
      image: redis:alpine
      container_name: ci3-ultimate-redis

    mysql:
      image: mysql:8.0
      container_name: ci3-ultimate-mysql
      volumes:
        - .:/app
      environment:
        - MYSQL_ROOT_PASSWORD=rootuser
        - MYSQL_DATABASE=dbname
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpassword
      ports:
        - "7375:3306"

    webserver:
      image: nginx:alpine
      container_name: ci3-ultimate-webserver
      volumes:
          - .:/app
          - ./bin/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7373:80"

    php-fpm:
      build: bin/phpdocker/php-fpm
      container_name: ci3-ultimate-php-fpm
      volumes:
        - .:/app
        - ./bin/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    composer:
      image: composer:1.10.5
      command: ["composer", "install"]
      volumes:
        - .:/app
      depends_on:
        - php-fpm

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - 7374:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
      depends_on:
        - mysql